name: agriconnect
description: "A mobile app promoting African local agriculture."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # State Management
  provider: ^6.1.5

  # Firebase Services
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.1
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.5.1

  # Local Storage
  shared_preferences: ^2.2.2

  # Networking
  http: ^0.13.6

  # Image Uploads
  image_picker: ^1.0.7

  # Notifications & Messaging
  fluttertoast: ^8.2.2
  firebase_messaging: ^14.7.9

  # Maps & Location Services
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.0

  # File Handling
  path_provider: ^2.1.2

  # Caching & Offline Support
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/

  # Custom Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
