name: agriconnect
description: "A mobile app promoting African local agriculture."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # State Management
  provider: ^6.1.2  # ✅ Updated provider version

  # Firebase Services
  firebase_core: ^2.25.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.8.0
  firebase_crashlytics: ^3.5.0
  firebase_analytics: ^10.8.0

  # Local Storage
  shared_preferences: ^2.3.0
  flutter_secure_storage: ^9.2.0  # Securely store sensitive data

  # Networking
  http: ^1.2.0

  # Image Uploads
  image_picker: ^1.1.0

  # Notifications & Messaging
  fluttertoast: ^8.2.4  # ✅ Updated fluttertoast version
  flutter_local_notifications: ^16.3.0  # Native notifications

  # Maps & Location Services
  geolocator: ^11.1.0
  google_maps_flutter: ^2.7.0

  # File Handling
  path_provider: ^2.1.2

  # Caching & Offline Support
  hive: ^2.2.3  # ✅ Fixed Hive Version
  hive_flutter: ^1.1.0  # ✅ Fixed Hive Flutter Version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # ✅ Assets (Fixed Paths)
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/Poppins-Regular.ttf
    - assets/fonts/Poppins-Bold.ttf

  # ✅ Custom Fonts (Fixed)
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
